[package]
name = "kubecfg-pack"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.13.0"
serde_yaml = "0.8.23"
structopt = "0.3.25"
